# Generated by Django 3.0.8 on 2020-09-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question2',
            old_name='answer1',
            new_name='answer2',
        ),
    ]
