# Generated by Django 3.0.8 on 2020-09-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200914_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('answer1', models.CharField(max_length=20, unique=True)),
                ('answer2', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CreateName',
        ),
        migrations.DeleteModel(
            name='Question1',
        ),
        migrations.DeleteModel(
            name='Question2',
        ),
    ]
