# Generated by Django 3.0.8 on 2020-09-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200914_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='answer1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='app',
            name='answer2',
            field=models.CharField(max_length=20),
        ),
    ]
